### ISSUE TITLE
How to use Triangle.dll?

### ISSUE THREAD

**Issue by electroremy** [eppz/Triangle.NET#2]
Hi,

Is it possible to get a "how-to-use" for the Triangle.dll file, with some samples ?

It will be usefull to use triangle.dll in a application.

Thanks

**Comment by eppz** [comment]
Hi, as I pointed out in `README`, I'm not the author of the library. Codeplex is shut down, but seems you can still access some archive material there. See [Triangle.NET at Codeplex](https://archive.codeplex.com/?p=triangle) for more.
